name: Linux ARM (Docker)

on:
  pull_request:
    types: [synchronize, opened]
  push:
    branches:
      - master

env:
  DEBIAN_FRONTEND: noninteractive
  OPENCV_VERSION: 4.5.5
  LIBICONV_VERSION: 1.16

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Install dependencies
        run: |
          pwd
          echo ${GITHUB_WORKSPACE}
          current_path=$(pwd)
          sudo apt-get update -y 
          sudo apt-get install -y  --no-install-recommends \
            apt-transport-https \
            software-properties-common \
            wget \
            unzip \
            ca-certificates \
            build-essential \
            cmake \
      - uses: docker/setup-buildx-action@v1
        with:
          install: true

      - uses: docker/setup-qemu-action@v1
    
      - name: Build libiconv
        run: |
          mkdir libiconv
          wget https://ftp.gnu.org/pub/gnu/libiconv/libiconv-${LIBICONV_VERSION}.tar.gz -Olibiconv-${LIBICONV_VERSION}.tar.gz && tar -zxvf libiconv-${LIBICONV_VERSION}.tar.gz
          cd libiconv-${LIBICONV_VERSION} && ls && ./configure --prefix=/usr/local --host=arm-linux && sudo make \ make install
      - name: Build with Docker
        run: |
          # Override OpenCV version in Dockerfile
          docker build \
            -t opencvsharp-linux-arm:latest \
            --output=type=docker \
            --platform=linux/arm/v7 \
            --build-arg OPENCV_VERSION \
            ./docker/ubuntu18-dotnetcore3.1-opencv4.5.3

      - name: Extract build files from Docker instance
        run: |
          docker create -ti --name opencvsharp-linux-arm-tmp opencvsharp-linux-arm bash
          docker cp opencvsharp-linux-arm-tmp:/artifacts .

      - name: Patch nuspec with version and build NuGet package
        run: |
          sed -E --in-place=.bak "s/<version>[0-9]\.[0-9]{1,2}\.[0-9]{1,2}.[0-9]{8}(-beta[0-9]*)?<\/version>/<version>${OPENCV_VERSION}.$(date '+%Y%m%d')<\/version>/" nuget/OpenCvSharp4.runtime.linux-arm.nuspec
          cp artifacts/libOpenCvSharpExtern.so nuget/
          dotnet pack nuget/OpenCvSharp4.runtime.linux-arm.csproj -o artifacts_arm

      - uses: actions/upload-artifact@v2
        with:
          name: artifacts_linux_arm
          path: artifacts_arm
